# Generated by Django 5.2.7 on 2025-10-19 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('file', models.FileField(upload_to='videos/', verbose_name='Відеофайл')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='videos/thumbs/', verbose_name='Постер')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Відео',
                'verbose_name_plural': 'Відео',
                'ordering': ['-created_at'],
            },
        ),
    ]
