# Generated by Django 5.2.7 on 2025-10-19 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва категорії')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='videos/cat_icons/', verbose_name='Іконка')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Категорія відео',
                'verbose_name_plural': 'Категорії відео',
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='video',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='videos', to='videos.videocategory', verbose_name='Категорія'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['slug'], name='videos_vide_slug_92e2bf_idx'),
        ),
    ]
