# Generated by Django 5.2.7 on 2025-11-25 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_videocategory_video_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='source',
            field=models.CharField(choices=[('upload', 'Завантажений файл'), ('youtube', 'YouTube')], db_index=True, default='upload', max_length=12, verbose_name='Джерело'),
        ),
        migrations.AddField(
            model_name='video',
            name='youtube_url',
            field=models.URLField(blank=True, verbose_name='YouTube URL'),
        ),
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='Відеофайл'),
        ),
    ]
