# Generated by Django 5.2.7 on 2025-11-25 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_video_source_video_youtube_url_alter_video_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='source',
        ),
        migrations.AlterField(
            model_name='video',
            name='youtube_url',
            field=models.URLField(blank=True, verbose_name='Посилання на YouTube'),
        ),
    ]
