# Generated by Django 5.2.7 on 2025-11-22 17:31

import django.db.models.deletion
import profiles.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=50, verbose_name='Прізвисько')),
                ('country', models.CharField(blank=True, max_length=80, verbose_name='Країна')),
                ('gender', models.CharField(blank=True, choices=[('f', 'Жінка'), ('m', 'Чоловік'), ('o', 'Інше')], max_length=1, verbose_name='Стать')),
                ('age_group', models.CharField(blank=True, choices=[('under13', 'До 13'), ('13-17', '13–17'), ('18+', '18+')], max_length=10, verbose_name='Вік')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='День народження')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=profiles.models.avatar_path, verbose_name='Аватар')),
                ('bio', models.TextField(blank=True, verbose_name='Про себе')),
                ('newsletter_opt_in', models.BooleanField(default=False, verbose_name='Отримувати новини')),
                ('terms_accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='Погоджено з умовами')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профіль',
                'verbose_name_plural': 'Профілі',
            },
        ),
    ]
