# Generated by Django 5.2.7 on 2025-10-28 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_post_options_remove_post_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postimage',
            name='width_percent',
            field=models.PositiveSmallIntegerField(default=50, help_text='Від 20 до 100, наприклад 50 = половина рядка.', verbose_name='Ширина (%)'),
        ),
    ]
