# Generated by Django 5.2.7 on 2025-10-28 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_postimage_width_percent'),
    ]

    operations = [
        migrations.CreateModel(
            name='WinxCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Імʼя')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('bg_color', models.CharField(default='#e96005', help_text='CSS колір: #hex або rgb/rgba', max_length=20, verbose_name='Колір фону')),
                ('badge_color', models.CharField(blank=True, help_text='Порожньо = як фон', max_length=20, verbose_name='Колір бейджа')),
                ('wings', models.ImageField(upload_to='core/winx/', verbose_name='Крила')),
                ('body', models.ImageField(upload_to='core/winx/', verbose_name='Тіло')),
                ('frame', models.ImageField(upload_to='core/winx/', verbose_name='Рамка')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показувати')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Winx картка',
                'verbose_name_plural': 'Winx картки',
                'ordering': ['order', 'id'],
            },
        ),
    ]
