# Generated by Django 5.2.7 on 2025-11-01 14:44

import core.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_winxcard'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['-created_at'], 'verbose_name': 'Квіз', 'verbose_name_plural': 'Квізи'},
        ),
        migrations.AddField(
            model_name='quiz',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Показувати на сайті'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='shuffle_options',
            field=models.BooleanField(default=True, verbose_name='Міксувати відповіді'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='shuffle_questions',
            field=models.BooleanField(default=False, verbose_name='Міксувати питання'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='slug',
            field=models.SlugField(blank=True, max_length=140, unique=True),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='width_percent',
            field=models.PositiveSmallIntegerField(default=50, verbose_name='Ширина (%)'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='description',
            field=models.CharField(blank=True, max_length=300, verbose_name='Підзаголовок'),
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Питання')),
                ('image', models.ImageField(blank=True, null=True, upload_to=core.models.quiz_upload, verbose_name='Картинка до питання')),
                ('order', models.PositiveIntegerField(default=0)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.quiz')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuizResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Напр., bloom / flora / A / B / C', max_length=10, verbose_name='Код')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('image', models.ImageField(blank=True, null=True, upload_to=core.models.quiz_upload, verbose_name='Зображення')),
                ('order', models.PositiveIntegerField(default=0)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='core.quiz')),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('quiz', 'code')},
            },
        ),
        migrations.CreateModel(
            name='QuizOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=500, verbose_name='Варіант')),
                ('image', models.ImageField(blank=True, null=True, upload_to=core.models.quiz_upload, verbose_name='Картинка до варіанту')),
                ('weight', models.PositiveSmallIntegerField(default=1, verbose_name='Вага')),
                ('order', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='core.quizquestion')),
                ('result', models.ForeignKey(help_text='До якого результату зараховуємо відповідь', on_delete=django.db.models.deletion.PROTECT, related_name='options', to='core.quizresult')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
