# Generated by Django 5.2.7 on 2025-11-01 15:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_quiz_options_quiz_created_at_quiz_is_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quizquestion',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Питання', 'verbose_name_plural': 'Питання'},
        ),
        migrations.AlterModelOptions(
            name='quizresult',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Результат', 'verbose_name_plural': 'Результати'},
        ),
        migrations.AlterUniqueTogether(
            name='quizresult',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='description',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='shuffle_options',
        ),
        migrations.AddField(
            model_name='quiz',
            name='shuffle_answers',
            field=models.BooleanField(default=False, verbose_name='Міксувати відповіді'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='subtitle',
            field=models.CharField(blank=True, max_length=300, verbose_name='Підзаголовок'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, unique=True),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='quiz/q/', verbose_name='Зображення відповіді/питання'),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.quiz', verbose_name='Квіз'),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='text',
            field=models.CharField(max_length=300, verbose_name='Питання'),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='code',
            field=models.CharField(db_index=True, max_length=5, verbose_name='Код (A/B/C/…)'),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='quiz/r/', verbose_name='Зображення результату'),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='core.quiz', verbose_name='Квіз'),
        ),
        migrations.CreateModel(
            name='QuizAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=300, verbose_name='Відповідь')),
                ('image', models.ImageField(blank=True, null=True, upload_to='quiz/a/', verbose_name='Зображення відповіді')),
                ('code', models.CharField(blank=True, max_length=5, verbose_name='Код (A/B/C/…)')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Правильна')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='core.quizquestion', verbose_name='Питання')),
            ],
            options={
                'verbose_name': 'Відповідь',
                'verbose_name_plural': 'Відповіді',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.DeleteModel(
            name='QuizOption',
        ),
        migrations.RemoveField(
            model_name='quizresult',
            name='description',
        ),
    ]
