# Generated by Django 5.2.7 on 2025-11-09 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_poll_polloption'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва')),
                ('position', models.CharField(choices=[('top', 'Над шапкою')], db_index=True, default='top', max_length=20, verbose_name='Позиція')),
                ('image', models.ImageField(upload_to='ads/', verbose_name='Зображення')),
                ('alt', models.CharField(blank=True, max_length=200, verbose_name='ALT-текст')),
                ('link_url', models.URLField(blank=True, verbose_name='Посилання')),
                ('open_new_tab', models.BooleanField(default=True, verbose_name='Відкривати у новій вкладці')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('start_at', models.DateTimeField(blank=True, null=True, verbose_name='Почати показ')),
                ('end_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершити показ')),
                ('weight', models.PositiveIntegerField(default=1, help_text='Більше = частіше показ', verbose_name='Вага (пріоритет)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Рекламний банер',
                'verbose_name_plural': 'Рекламні банери',
                'ordering': ['-weight', '-created_at'],
            },
        ),
    ]
