# Generated by Django 5.2.7 on 2025-10-19 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва категорії')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='gallery/cat_icons/', verbose_name='Іконка')),
            ],
            options={
                'verbose_name': 'Категорія галереї',
                'verbose_name_plural': 'Категорії галереї',
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='album',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='albums', to='gallery.gallerycategory', verbose_name='Категорія'),
        ),
    ]
