# Generated by Django 5.2.7 on 2025-10-25 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_alter_photo_options_album_cover_photo_position'),
    ]

    operations = [
    ]
