# Generated by Django 5.2.7 on 2025-10-19 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('engine', models.CharField(choices=[('ruffle', 'Ruffle (Flash)')], default='ruffle', max_length=20, verbose_name='Двигун')),
                ('swf_file', models.FileField(upload_to='games/swf/', verbose_name='SWF файл')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='games/covers/', verbose_name='Обкладинка')),
                ('width', models.PositiveIntegerField(default=800, verbose_name='Ширина')),
                ('height', models.PositiveIntegerField(default=600, verbose_name='Висота')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Гра',
                'verbose_name_plural': 'Ігри',
                'ordering': ['-created_at'],
            },
        ),
    ]
