# Generated by Django 5.2.7 on 2025-10-19 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва категорії')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='games/cat_icons/', verbose_name='Іконка')),
            ],
            options={
                'verbose_name': 'Категорія ігор',
                'verbose_name_plural': 'Категорії ігор',
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='game',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='games', to='games.gamecategory', verbose_name='Категорія'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['slug'], name='games_game_slug_161310_idx'),
        ),
    ]
