# Generated by Django 5.2.7 on 2025-10-25 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_gamecategory_game_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва тематики')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='games/theme_icons/', verbose_name='Іконка')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='games/theme_covers/', verbose_name='Обкладинка')),
            ],
            options={
                'verbose_name': 'Тематика ігор',
                'verbose_name_plural': 'Тематики ігор',
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='gamecategory',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='categories', to='games.gametheme', verbose_name='Тематика'),
        ),
    ]
